[package]
name = "project-soyuz"
version = "0.1.0"
authors = ["David Futcher <david@futcher.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasmer-runtime="0.17"
